# Generated by Django 5.0.1 on 2024-02-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionresult',
            name='comment',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
