# Generated by Django 5.0.1 on 2024-02-01 14:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_competitionjudgment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='judgment',
            field=models.ManyToManyField(related_name='competition_judges', through='events.CompetitionJudgment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='competition',
            name='participants',
            field=models.ManyToManyField(related_name='competition_participants', through='events.CompetitionResult', to=settings.AUTH_USER_MODEL),
        ),
    ]
