ARG NODE_VERSION=20.10.0

FROM node:${NODE_VERSION}-alpine as base

ENV NODE_ENV=development

WORKDIR /src

FROM base as build

COPY --link ../../frontend/package.json ../../frontend/yarn.lock ./
RUN yarn install 

FROM base

COPY --from=build /src/node_modules /src/node_modules

