# Generated by Django 5.0.1 on 2024-02-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='belt',
            name='id',
        ),
        migrations.AlterField(
            model_name='belt',
            name='code',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
