# Generated by Django 5.0.1 on 2024-01-31 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_baseuser_links'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseuser',
            old_name='is_coach',
            new_name='is_staff',
        ),
    ]
