# Generated by Django 5.0.1 on 2024-01-31 20:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_is_coach_baseuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None),
        ),
    ]
