# Generated by Django 5.0.1 on 2024-01-31 20:51

import django_better_admin_arrayfield.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_baseuser_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='links',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None),
        ),
    ]
