# Generated by Django 5.0.1 on 2024-02-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceuser',
            name='comment',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
