global:
  checkNewVersion: true
  sendAnonymousUsage: false

# serversTransport:
#   insecureSkipVerify: true

entryPoints:
  http:
    address: :80


providers:
  providersThrottleDuration: 2s

  # File provider for connecting things that are outside of docker / defining middleware
  file:
    filename: /etc/traefik/fileConfig.yaml
    watch: true

  # Docker provider for connecting all apps that are inside of the docker network
  docker:
    watch: true
    network: proxy
    exposedByDefault: false

# Enable traefik ui
api:
  dashboard: true
  insecure: true

# Log level INFO|DEBUG|ERROR
log:
  level: INFO

# # Use letsencrypt to generate ssl serficiates
# certificatesResolvers:
#   letsencrypt:
#     acme:
#       email: YOUR@EMAIL.COM
#       storage: /etc/traefik/acme.json
#       dnsChallenge:
#         provider: cloudflare
#         # Used to make sure the dns challenge is propagated to the rights dns servers
#         resolvers:
#           - "1.1.1.1:53"
#           - "1.0.0.1:53"