# Generated by Django 5.0.1 on 2024-02-01 10:29

import ckeditor.fields
import django.db.models.deletion
import django_jsonform.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('text', ckeditor.fields.RichTextField(verbose_name='news text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('images', django_jsonform.models.fields.ArrayField(base_field=models.ImageField(blank=True, upload_to='news/%Y/%m/%d'), size=10)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
    ]
