# Generated by Django 5.0.1 on 2024-02-01 12:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='participants',
            field=models.ManyToManyField(related_name='group_participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
